Feat/update and delete
monosparta/post-frontend pull request #2
Opened 2022-10-21 07:47 UTC by Nopeta

功能：
1. 我的文章介面建置
2. 將axios的API建置成store(posts.store)
3. 新增刪除功能放置於ShowPost.vue元件

修正：
1. 刪除功能執行時modal 顯示的文字調整
5. 新增與編輯文章顯示的按鈕元件，將其重複的code進行優化
6. 移除原抓取cookie的userid設定，改以user.store已儲存的userid使用
7. 修正編輯文章畫面沒有顯示文章的內容
8. 修正我的文章與首頁 tab跳轉的code寫法

2022-10-21 10:04 UTC, jimchen5209 requested changes

2022-10-21 10:04 UTC, jimchen5209 commented on src/components/parts/ShowPost.vue
> +  await post.clearReturnInfo()
這個不是 async function，不需要 await

2022-10-21 13:41 UTC, Nopeta reviewed
已經ShowPost.vue不需要的async/await移除。

2022-10-24 01:42 UTC, jimchen5209 commented on src/components/parts/ShowPost.vue
> +  post.deletePost(props.id!)
等等 deletePost 還是 async function 吧

2022-10-24 01:54 UTC, Nopeta commented on src/components/parts/ShowPost.vue
> +  post.deletePost(props.id!)
是保留async 但await不需要嗎？

2022-10-24 01:59 UTC, jimchen5209 commented on src/components/parts/ShowPost.vue
> +  post.deletePost(props.id!)
clearReturnInfo 在定義那邊沒有 async 所以這裡不需要 await
![image](https://user-images.githubusercontent.com/10269287/197432932-f211bc57-ab84-4b2b-a234-2478a4acd8d4.png)

但是 deletePost 還是有 async 所以 await 還是需要的
![image](https://user-images.githubusercontent.com/10269287/197432984-82b20c57-97d6-4cc5-8ab6-8f298468ebc1.png)

2022-10-24 02:08 UTC, Nopeta commented on src/components/parts/ShowPost.vue
> +  post.deletePost(props.id!)
感謝！了解了！

2022-10-24 02:39 UTC, Nopeta commented
已更改並修正上週code reviwe所建議與改善之細項

2022-10-24 02:44 UTC, jimchen5209 approved these changes

2022-10-24 02:46 UTC, merged